version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecoride_app
    volumes:
      - .:/var/www/html
    environment:
      APP_ENV: dev
    depends_on:
      - mysql
      - mongo
    expose:
      - "9000"

  mysql:
    image: mysql:8.0-oracle
    container_name: ecoride_mysql
    restart: always
    environment:
      MYSQL_DATABASE: ecoride
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ecoride
      MYSQL_PASSWORD: ecoride
    command: --default-authentication-plugin=mysql_native_password --ssl=0 --skip-ssl
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  mongo:
    image: mongo:7.0
    container_name: ecoride_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_app
    restart: always
    depends_on:
      - mysql
      - mongo
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www/html

  nginx:
    image: nginx:stable-alpine
    container_name: symfony_nginx
    restart: always
    depends_on:
      - php
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  mysql_data:
  mongo_data: 