version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_php
    restart: always
    depends_on:
      - mysql
      - mongo
    volumes:
      - ./:/var/www/html
    expose:
      - "9000"

  mysql:
    image: mysql:8.0-oracle
    container_name: symfony_mysql
    restart: always
    environment:
      MYSQL_DATABASE: ecoride
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ecoride
      MYSQL_PASSWORD: ecoride
    command: --default-authentication-plugin=mysql_native_password --ssl=0 --skip-ssl
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  mongo:
    image: mongo:7.0
    container_name: symfony_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  nginx:
    image: nginx:stable-alpine
    container_name: symfony_nginx
    re
