services:
  - type: web
    name: ecoride
    env: static
    plan: free
    branch: main
    buildCommand: "composer install --no-dev --optimize-autoloader"
    startCommand: "php -S 0.0.0.0:10000 -t public"
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_DEBUG
        value: "0"
      - key: APP_SECRET
        generateValue: true
      - key: DATABASE_URL
        value: mysql://TONUSER:TONPASS@TONHOST:3306/TONNOMDEBASE
      - key: MONGODB_URL
        value: mongodb+srv://TONUSER:TONPASS@toncluster.mongodb.net/TONDB