services:
  - type: web
    name: ecoride
    env: static
    plan: free
    branch: main
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php bin/console cache:clear --env=prod
      php bin/console doctrine:migrations:migrate --env=prod --no-interaction
    startCommand: "php -S 0.0.0.0:10000 -t public"
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_DEBUG
        value: "0"
      - key: APP_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: ecoride-db
          property: connectionString
      - key: MONGODB_URL
        value: "mongodb+srv://username:password@cluster.mongodb.net/ecoride"

databases:
  - name: ecoride_db
    databaseName: ecoride
    user: ecoride_user